# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7555a905bfb0b9f47c8826e5a2db0ce45553e1c36e3de2c92fc5a109b09bd296241990057bd336f3e8dc439ff1d68ced00acef86719a4df8f95e4a0f4893c506

test:
  secret_key_base: 488c580eb6115b136476009ce9bbc9f7a0cdf70ea029e2c21c65d260aaed84efa532bcb77e68fabefe51d6586245d033a2c26846c644d4fc794d20061e64eb20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
